module.exports = {
  ACCESS_TOKEN_SECRET:  process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY:  '15m',  
  REFRESH_TOKEN_EXPIRY: '15m',   
  GITHUB_CLIENT_ID:     process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GITHUB_CALLBACK_URL:  process.env.GITHUB_CALLBACK_URL,
};
